### ISSUE TITLE
Test and document setting up ss on a cloud provider

### ISSUE THREAD

**Issue by silentrob** [superscriptjs/superscript#208]
Lets verify everything works for EC2 and Ubuntu.

**Comment by silentrob** [comment]
So I have verified this does work on ubuntu again on EC2, but was not able to document the setup steps myself. (The VM was handed over pre-setup)

**Comment by Lewwwk** [comment]
We are also running on an ec2 t2.micro. In addition to the bot we are also running a web server and currently bump up just over 500MB of memory occasionally. We were on Heroku before but it uses and ephemeral storage system so the level DB would get blown out with every restart. On our ec2, we have a shared folder that persists where we keep the levelDB now so that it persists.

**Comment by benhjames** [comment]
Have pushed some docs on getting set up on Heroku to the v1 branch of the wiki.

In the future, we could look to write a `Deploy to Heroku` button that I've seen on some repos before - a one-click button to provision everything on a server that you need.
