### ISSUE TITLE
Multiligual Trigger support

### ISSUE THREAD

**Issue by belync** [superscriptjs/superscript#260]
I wish superscript can support double byte trigger. Like Chinese etc. Right now it seems only support western language.

**Comment by benhjames** [comment]
This would be great, but supporting other languages would involve a non-trivial (large) amount of work spanning several projects, since we do things like POS tagging, normalising and other forms of matching (specific to a language) that would need adding to. I think this is out of scope unless someone spearheads a project to support all the necessary groundwork we'd need to do to do this. :)

**Comment by silentrob** [comment]
With some of the work involved in getting to 1.0 we have made things a little easier for supporting more latin languages. Bot-lang could have a language switch, and custom plugins could make matching mostly work in ss-message.
