### ISSUE TITLE
Pass topicName as an extraScope in reply function is not working

### ISSUE THREAD

**Issue by zapbuild** [superscriptjs/superscript#291]
@silentrob  @Lewwwk @Laurian @Rajan @wehriam 

## Expected Behavior

When I pass the topicName as 4th parameter in reply function then it should search in that topic only.
Eg. I have passed like 

botInstance.reply(user_id, 'Hi, how are you?', function(err, resObj){},{ topicName:'greetings' });

It should search in only 'greetings' topic gambits and replies.

## Current Behavior

But currently it searches in all topics in the system.

## Possible Solution

I have just review the code of superscript/index.js from line 190 to line 228. I found that the extraScope parameter again copied in options variable on line 199 like the following:

var options = {
    userId: userId,
    msgString: msg,
    extraScope: extraScope
  };

The above options passed in the _reply function

this._reply(options, callback);

Now if you see _reply function definition you see that 

var system = {
    // getReply
    topicsSystem: self.topicSystem,
    plugins: self._plugins,
    scope: self.scope,
    messageScope: options.extraScope,
    // Pass in the topic if it
    **topicName: options.topicName || null,**
    // Message
    question: self.question,
    normalize: self.normalize,
    facts: self.factSystem,
    editMode: self.editMode
  };

line 221 topicName: options.topicName || null,
should be written as topicName: options.extraScope.topicName || null,

 @@
## Context

I have a requirement that each user have their own topics and my chatbot should search in their own topics when logged in to the system. Different users will have their own topic and get the reply form their own topics.

**Comment by benhjames** [comment]
Sorry for the late reply! I think there are a couple things with this.

Firstly, you really don't want to let different users have their own topics, because if a reply doesn't match in a topic, it will by default check all the other topics for a reply, so you'll end up sending back another user's reply!

Instead, you'd probably want to create a script or Mongo database for each user, and have SuperScript call into a user-specific database with all the user-specific data.

Secondly, I think the `extraScope` parameter may have been misunderstood: this is used as a way of giving additional data to all plugins, so you can access some user-specific data within the plugins per reply. It won't define any topic flow or anything, it's just a bit of data you can get at runtime.

Hope that helps!
