### ISSUE TITLE
Question : What about performance ?

### ISSUE THREAD

**Issue by davidchriqui** [superscriptjs/superscript#302]
Hi,

I wonder how well is performing Superscript in a production environment with +10k simultaneous users ?

Is it possible to scale horizontally with superscript ? Nodejs session management is maybe where to look for ?

Anyone already have metrics about performance ?

Thank you

**Comment by benhjames** [comment]
So profiling is something I really want to try out and was thinking about yesterday. I'm probably seeing about ~100ms (a guess) a reply on the v1.0.0 alpha branch for simple scripts, but over the next couple weeks with v1 starting to ready up for launch, I'd like to get some more reliable figures.

I imagine most of that time is spent doing normalisation and regex matching.

Part of the work we've done over the last couple weeks has been about enabling SuperScript to scale. In my mind, I imagined that if you wanted a large number of users, you'd put SS in a cloud function and host it on AWS or somewhere, so it'll scale automagically. I only say that because I have quite limited knowledge of production scaling.

I also would like to focus on performance in the future. For example (off the top of my head), if you know ahead of time where a redirect lands, we could introduce some markup to go directly to it instead of searching through everything again.

Anyway, an ambiguous response that will hopefully be clarified when we do some proper profiling!

I think a few people are running SS in production too who might know more. 😄

**Comment by Samurais** [comment]
The bot.reply turn around in ~100ms, it seems great. But how many gambits and replies do you have? I also give it a try in production. A big challenge is to make ss stateless, so it is easy to scale out or scale in. Right not, there is a LevelDB for the Fact System, I dont have much knowledge.

**Comment by benhjames** [comment]
So ~100ms is a very rough estimate for around 20/30 gambits = a very very simple bot. It'd be good to try out timings for greater numbers of gambits/replies!

v1 has ripped out the LevelDB file system and put the backing store in MongoDB (still Level interface) so it should now be entirely stateless, which was a key goal and should allow you to scale on multiple servers/functions/whatever.

**Comment by benhjames** [comment]
I did some more profiling of a bot being served on an Express server using the excellent [bench-rest](https://github.com/jeffbski/bench-rest) library. Bear in mind these are all on `localhost` so there's no database fetch delay etc.

On a bot with a single trigger I'm getting times averaging 20ms for a single reply (~50 requests a second). This should give a rough indication of the overall overheads of doing a request. If you bump the number of concurrent requests to 5 simultaneous messages, it degrades to about 115ms a request, still pretty good really considering the amount of work it's doing behind the scenes.

Pushing that up to sixty triggers, I'm getting 50ms for a single reply (~20 requests a second), or 220ms each for 5 concurrent requests, still all pretty good and definitely able to cope with real-time chat (in fact, a user wouldn't even notice the delay!)

Putting the database onto a server is a different story, but hopefully these figures give some insight into the time taken for responses. :)
