### ISSUE TITLE
this.message.props does not work as expected

### ISSUE THREAD

**Issue by Samurais** [superscriptjs/superscript#329]
Write a custom plugin, call plugin from script. Use **this.message.props['key'] = value** which is described in [wiki](https://github.com/superscriptjs/superscript/wiki/Plugins-and-Functions#out-of-bound-data).

## Expected Behavior

With the bot.reply method, get the key-values in callback.

## Current Behavior

Get an error. 
```
There was an error processing reply tags: TypeError: Cannot set property 'WHAT_PROPERTY' of undefined
```

## Possible Solution

After check the keys in **this.message**, it does not contain *props* object.

![image](https://cloud.githubusercontent.com/assets/3538629/24069977/df952938-0bee-11e7-9a59-b9c304328915.png)
![image](https://cloud.githubusercontent.com/assets/3538629/24069981/e8ee7b88-0bee-11e7-8373-e94b5da60509.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: ss1.0.6
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): node 7.7.1
* Server type and version: Mac OSX
* Operating System and version:
* Link to your project:

**Comment by benhjames** [comment]
Because the plugin function creates a copy of the `message` object, modifying the `message.props` object won't persist once it leaves the function.

Instead, you'll want to do as described [here](https://github.com/superscriptjs/superscript/wiki/Plugins-and-Functions#returning-props-to-send-back-in-the-final-message). Essentially we pass back props in the callback which will then be merged into the "real" message object!

**Comment by benhjames** [comment]
Guessing this is OK - closing!
